### ISSUE TITLE
[Help]: Where to set environment variables without using docker?

### ISSUE THREAD

**Issue by Hoshino-Yukino** [khakers/modmail-viewer#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v0.6.4

### In which part of the application does the error occur?

Unknown/both

### Current Behavior

If I don't use docker and run modmail directly by downloading tar, where should I configure environment variables such as MODMAIL_VIEWER_MONGODB_URI

### Environment

```Markdown
- OS: Ubuntu 20.04
- Java: 17.0.7
```

### Relevant log output

```Shell
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.github.khakers.modmailviewer.Main.main(Main.java:72)
Caused by: java.lang.IllegalArgumentException: No mongodb URI provided. provide one with the option "MODMAIL_VIEWER_MONGODB_URI"
        at org.apache.logging.log4j.core.util.Assert.requireNonEmpty(Assert.java:96)
        at com.github.khakers.modmailviewer.Config.<clinit>(Config.java:26)
        ... 1 more
```

**Comment by khakers** [comment]
This is a bit of a broad Linux question since it heavily depends on how you're running the application. 


If you're using systemd, for instance, you could set them in your unit file

**Comment by Hoshino-Yukino** [comment]
这是来自QQVIP邮箱的自动回复邮件。
